### ISSUE TITLE
Disable the unique posts permalink

### ISSUE THREAD

**Issue by florentsorel** [KLicheR/wp-polylang-translate-rewrite-slugs#6]
Hi,

It would be great if your plugin can allow the same post link structure.
For example :

In your example :

```
add_filter('pll_translated_post_type_rewrite_slugs', function($post_type_translated_slugs) {
    // Add translation for "product".
    $post_type_translated_slugs['product'] = array(
        'en' => 'products',
        'fr' => 'produits',
    );
    return $post_type_translated_slugs;
});
```

I create a product with "camembert" permalink and I add the translatation but the english translation is the same. So I have "camembert-2".

It's possible to disable the functionnality of WordPress to have a solution bellow:

fr => fr/produits/camembert
en => en/products/camembert

**Comment by MALIK-0** [comment]
Hi KLicheR did you find anything to solve this annoying behaviour?

**Comment by chesio** [comment]
Hi Tobias,
I believe this is exactly what [Polylang Slug](https://github.com/grappler/polylang-slug) plugin does.

Cheers,
Česlav

**Comment by MALIK-0** [comment]
Hi chesio,

looked at both plugins and think "wp-polylang-translate-rewrite-slugs" may offers what I need.
Maybe someone could give me an advice to archive this structure.

I have a page name/taxonomy slug "customers" which should be translated into other languages, but the actual post should be named the same in different languages. Example:

**http://example.com/referenzen/john-doe** (default language, german)
**http://example.com/en/references/john-doe** (english, slug translated, post name stays)

Actual I have only the Polylang plugin installed, so page name "referenzen" gets translated properly. But Wordpress changes the post name (customer name) to "john-doe-1" because permalinks have to be unique.

So the question is: **How can I translate the page name/taxonomy slug but keep the postname the same in different languages?**

**Comment by grappler** [comment]
@TobiasMalikowski It is not clear what the data is from your URL. So "customers" is a custom post type and "john-doe" is a post title.
http://example.com/customers/john-doe
http://example.com/{post-type}/{post-title}

This plugin only allows you to translate the custom post type. To fix having the same slug in two different languages you can use the Polylang Slug plugin. You can see it in action here: https://wpzoo.ch/en/blog/

**Comment by MALIK-0** [comment]
@grappler Thanks for the quick reply and sorry for beeing not clear. I will clear things up now.

I have 2 languages (german = default, english = second language) and the following structure:

http://example.com**/{post-type}/{post-title}** (variables)

But WordPress won't let me use the same {post-title} for both languages, so it appends a "-1" to the post-title.

**What I want:**
http://example.com**/referenzen/john-doe** (german)
http://example.com**/en/references/john-doe** (english, post-type translated, post-name stays)

**What WordPress does**
http://example.com**/referenzen/john-doe** (german)
http://example.com**/en/referenzen/john-doe-1** (english, post-type not translated, post-name gets -1 appended)

I think this plugin enables me to translate the post-type, but does this also solve the "-1" thing?

**Update**
I'm now using your plugin, applied the fix for Issue 34. The post-type now gets properly translated, but WordPress still appends "-1" to the post-title. Does anyone know how to fix this? My post-title should stay the same for all languages.

Ok I did alot of research and it looks like, this is a WordPress behaviour and is not changed by Polylang etc. Many people asked for a feature like this, but it never got implemented.

Some resources for people who want to read more upon this:

https://wordpress.org/support/topic/non-unique-slugs-and-an-other-question
https://wordpress.org/support/topic/plugin-polylang-identical-page-names-in-different-languages

I hope that someone got this to work ...
